### ISSUE TITLE
`Dockerfile`: Save space and remove ansible and python3 after use

### ISSUE THREAD

**Issue by chanwilson** [particleKIT/munin-docker#5]
Perhaps the overhead of using ansible on a base of OpenSUSE Leap isn't as bad as it is for other bases, but when I look at adapting this to a different linux flavor I find that pulling in Ansible adds a bunch unused stuff (ie all of python3 and related ansible requirements) to the container for a one-time use.

**Comment by martingabelmann** [comment]
Thanks for the hint.  

python3 is actually used within the container for generation of the munin inventory (when using `INVENTORY_GEN=list`), so we cant remove it after installing. 
However, removing ansible freed around 250MB...
  
The current setup is by far not optimal but was adapted from our non-docker installation... We eager for [munin3](https://github.com/particleKIT/munin3-docker) anyways, so major improvements/rewrites will most probably not happen..
